/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heywordframe;

import java.awt.Color;

/**
 *
 * @author jhone
 */
public class HeyFrame extends javax.swing.JFrame {

    /**
     * Creates new form HeyFrame
     */
    public HeyFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        JBottonResultado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcdxOperaciones = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtR = new javax.swing.JTextField();
        JbottonBorrar = new javax.swing.JButton();
        outexit = new java.awt.TextField();
        binario = new javax.swing.JRadioButton();
        hexa = new javax.swing.JRadioButton();
        OCTAL = new javax.swing.JRadioButton();
        Convertir = new javax.swing.JButton();
        converso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setBackground(new java.awt.Color(102, 153, 255));
        txt1.setForeground(new java.awt.Color(153, 255, 102));
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        txt2.setBackground(new java.awt.Color(0, 153, 255));
        txt2.setForeground(new java.awt.Color(102, 255, 153));
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        JBottonResultado.setBackground(new java.awt.Color(153, 255, 153));
        JBottonResultado.setForeground(new java.awt.Color(255, 0, 51));
        JBottonResultado.setText("Resultado");
        JBottonResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBottonResultadoActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("calcualdora");

        jcdxOperaciones.setForeground(new java.awt.Color(255, 0, 255));
        jcdxOperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--/---", "Suma", "Restar", "Multiplicar", "Dividir" }));
        jcdxOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcdxOperacionesActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("operaciónes ");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("variable 1");

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("variable 2");

        txtR.setBackground(new java.awt.Color(204, 102, 255));
        txtR.setForeground(new java.awt.Color(102, 255, 102));
        txtR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRActionPerformed(evt);
            }
        });

        JbottonBorrar.setBackground(new java.awt.Color(102, 102, 255));
        JbottonBorrar.setForeground(new java.awt.Color(255, 0, 0));
        JbottonBorrar.setText("borrar");
        JbottonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbottonBorrarActionPerformed(evt);
            }
        });

        outexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outexitActionPerformed(evt);
            }
        });

        binario.setText("Binario");
        binario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarioActionPerformed(evt);
            }
        });

        hexa.setText("Hexadecimal");

        OCTAL.setText("octal");
        OCTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCTALActionPerformed(evt);
            }
        });

        Convertir.setBackground(new java.awt.Color(153, 255, 153));
        Convertir.setForeground(new java.awt.Color(255, 0, 51));
        Convertir.setText("Convertir");
        Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirActionPerformed(evt);
            }
        });

        converso.setBackground(new java.awt.Color(204, 102, 255));
        converso.setForeground(new java.awt.Color(102, 255, 102));
        converso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(42, 42, 42))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Convertir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt2)
                                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(converso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JbottonBorrar)
                                            .addComponent(JBottonResultado)))
                                    .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OCTAL)
                            .addComponent(jcdxOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(binario)
                            .addComponent(hexa)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(outexit, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addComponent(JBottonResultado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(jcdxOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hexa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OCTAL)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(binario)
                    .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbottonBorrar)
                    .addComponent(converso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Convertir))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcdxOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcdxOperacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcdxOperacionesActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txtRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRActionPerformed

    private void JBottonResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBottonResultadoActionPerformed
        int operacion = jcdxOperaciones.getSelectedIndex();
        switch (operacion) {

            case 0:
                outexit.setText("Ingresa una operacion");
                txtR.setText(String.valueOf(0));
                txt1.setText(String.valueOf(0));
                txt2.setText(String.valueOf(0));
                break;
            case 1:
                outexit.setText("SUMA");
                if (OCTAL.isSelected() == true) {
                int sum1 = Integer.parseInt(txt1.getText());
                int sum2 = Integer.parseInt(txt2.getText());
                int resutado0 = (sum1 + sum2);
                txtR.setText(String.valueOf(resutado0));
                 
                }
                break;
            case 2:
                outexit.setText("Resta");
                int res1 = Integer.parseInt(txt1.getText());
                int res2 = Integer.parseInt(txt1.getText());
                int resutado1 = (res1 - res2);
                txtR.setText(String.valueOf(resutado1));

                break;
            case 3:
                outexit.setText("Multiplicacion");
                int mul1 = Integer.parseInt(txt1.getText());
                int mul2 = Integer.parseInt(txt1.getText());
                int resutado2 = (mul1 * mul2);
                txtR.setText(String.valueOf(resutado2));

                break;
            case 4:
                outexit.setText("Division");
                int div1 = Integer.parseInt(txt1.getText());
                int div2 = Integer.parseInt(txt1.getText());
                try {
                    int resultado3 = (div1 / div2);
                    txtR.setText(String.valueOf(resultado3));
                } catch (ArithmeticException ex) {
                    outexit.setText("error!!");
                }
                break;
            default:
                txtR.setText("mierda");
                break;
        }

// TODO add your handling code here:
    }//GEN-LAST:event_JBottonResultadoActionPerformed

    private void JbottonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbottonBorrarActionPerformed
        // ESTE ES EL METODO DE BORRAR
        txt1.setText("");
        txt2.setText("");
        txtR.setText("");
        converso.setText("");
        
        outexit.setText("Hola usuario");
    }//GEN-LAST:event_JbottonBorrarActionPerformed

    private void outexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outexitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outexitActionPerformed

    private void binarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_binarioActionPerformed

    private void OCTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OCTALActionPerformed

    private void ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirActionPerformed
        // TODO add your handling code here:
        outexit.setText("ingresa un numero para convertir");
//        txtR.setText("Aqui");
        if (binario.isSelected() == true) {
            //variables
            int dnum1 = Integer.parseInt(txtR.getText(), 2);
            String bi3;
            int br3;
            //conversion
            bi3 = Integer.toBinaryString(dnum1);
            //impresion
            converso.setText(String.valueOf(dnum1));
            }
        if (OCTAL.isSelected() == true) {

            int dnum1 = Integer.parseInt(txtR.getText(), 8);
            String bi3;
            String oc3;
            //conversion
//            dnum1=oc3;
            oc3 = Integer.toOctalString(dnum1);
            //impresion
            converso.setText(String.valueOf(dnum1));
            }

        if (hexa.isSelected() == true) {
            int dnum2 = Integer.parseInt(txtR.getText(), 16);
            String bi3;
            String hr3;
            //conversion
            hr3 = Integer.toHexString(dnum2);
            //impresion
            converso.setText(String.valueOf(dnum2));
        
        }
    }//GEN-LAST:event_ConvertirActionPerformed

    private void conversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conversoActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeyFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Convertir;
    private javax.swing.JButton JBottonResultado;
    private javax.swing.JButton JbottonBorrar;
    private javax.swing.JRadioButton OCTAL;
    private javax.swing.JRadioButton binario;
    private javax.swing.JTextField converso;
    private javax.swing.JRadioButton hexa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox jcdxOperaciones;
    private java.awt.TextField outexit;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtR;
    // End of variables declaration//GEN-END:variables
}
